FROM node:20-alpine as builder

WORKDIR /app

COPY . .
RUN npm install

FROM node:20-alpine

RUN apk add jq moreutils

WORKDIR /usr/app

COPY --from=0 /app/packages/azure-kusto-data/dist-esm/src dist-esm/src
COPY --from=0 /app/packages/azure-kusto-data/types/src types/src
COPY --from=0 /app/packages/azure-kusto-data/package.json package.json
COPY --from=0 /app/packages/azure-kusto-data/README.md README.md

COPY --from=0 /app/node_modules/.bin/uuid node_modules/.bin/uuid
COPY --from=0 /app/node_modules/@types/uuid node_modules/@types/uuid
COPY --from=0 /app/node_modules/uuid node_modules/uuid

COPY --from=0 /app/LICENSE LICENSE

RUN jq '.name = "@newboot-io/azure-kusto-node"' package.json | sponge package.json